import {
  AIProvider,
  StoryGenerationInput,
  StoryGenerationOutput,
  TextToSpeechInput,
  TextToSpeechOutput,
  TranslationInput,
  TranslationOutput,
} from '../interfaces';

/**
 * Mock AI provider for development and testing.
 * Returns placeholder content without calling any external API.
 */
export class MockAIProvider implements AIProvider {
  readonly name = 'mock';

  async generateStory(input: StoryGenerationInput): Promise<StoryGenerationOutput> {
    const startTime = Date.now();

    // Simulate processing delay
    await new Promise((resolve) => setTimeout(resolve, 1000));

    const content = `[Mock Story - ${input.language}]\n\nOnce upon a time, based on: "${input.prompt}"\n\nThis is a placeholder story generated by the mock AI provider. In production, this will be replaced with actual AI-generated content in ${input.language}.\n\nThe story would be told by an avatar with personality: ${input.avatarPersonality ?? 'default'}.\n\n-- End of mock story --`;

    return {
      content,
      title: `Mock Story: ${input.prompt.slice(0, 50)}`,
      metadata: {
        tokensUsed: content.length,
        model: 'mock-v1',
        generationTimeMs: Date.now() - startTime,
      },
    };
  }

  async generateSpeech(input: TextToSpeechInput): Promise<TextToSpeechOutput> {
    return {
      audioBuffer: Buffer.from('mock-audio-data'),
      format: 'mp3',
      durationMs: input.text.length * 50,
    };
  }

  async translate(input: TranslationInput): Promise<TranslationOutput> {
    return {
      translatedText: `[${input.targetLanguage}] ${input.text}`,
      confidence: 0.95,
    };
  }

  async healthCheck(): Promise<boolean> {
    return true;
  }
}
